export type Category = "공원·자연" | "한강" | "관광·역사" | "상권·역세권" | "야경·전망";
export const CATEGORIES = ["전체", "공원·자연", "한강", "관광·역사", "상권·역세권", "야경·전망"] as const;
export type CategoryFilter = (typeof CATEGORIES)[number];

export interface SeoulPlace {
  areaName: string; // Seoul citydata_ppltn API parameter (confirmed working)
  displayName: string;
  category: Category;
  // Hour range [start, end). 24h = {start:0, end:24}
  operatingHours: { start: number; end: number };
  lat: number;
  lng: number;
  description: string;
  place: string;
}

export const SEOUL_PLACES: SeoulPlace[] = [
  // ── 공원·자연 ─────────────────────────────────────────────
  {
    areaName: "남산공원",
    displayName: "남산공원",
    category: "공원·자연",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5512,
    lng: 126.9882,
    description: "도심 속 숲길 산책 명소",
    place: "중구 남산동",
  },
  {
    areaName: "서울숲공원",
    displayName: "서울숲",
    category: "공원·자연",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5444,
    lng: 127.0374,
    description: "성수동 도심 대형 공원",
    place: "성동구 성수동",
  },
  {
    areaName: "청계산",
    displayName: "청계산",
    category: "공원·자연",
    operatingHours: { start: 5, end: 20 },
    lat: 37.4419,
    lng: 127.0534,
    description: "서울 근교 인기 산행 코스",
    place: "서초구 원지동",
  },
  {
    areaName: "아차산",
    displayName: "아차산",
    category: "공원·자연",
    operatingHours: { start: 5, end: 20 },
    lat: 37.5524,
    lng: 127.1014,
    description: "한강이 한눈에 보이는 트레킹 명소",
    place: "광진구 광장동",
  },
  {
    areaName: "올림픽공원",
    displayName: "올림픽공원",
    category: "공원·자연",
    operatingHours: { start: 5, end: 22 },
    lat: 37.521,
    lng: 127.1198,
    description: "넓은 잔디광장과 문화공연 명소",
    place: "송파구 방이동",
  },
  {
    areaName: "서울대공원",
    displayName: "서울대공원",
    category: "공원·자연",
    operatingHours: { start: 9, end: 18 },
    lat: 37.4303,
    lng: 127.0081,
    description: "동물원·식물원 복합 테마파크",
    place: "과천시 막계동",
  },
  {
    areaName: "보라매공원",
    displayName: "보라매공원",
    category: "공원·자연",
    operatingHours: { start: 0, end: 24 },
    lat: 37.4918,
    lng: 126.9179,
    description: "동작구 대표 시민공원",
    place: "동작구 신대방동",
  },
  {
    areaName: "월드컵공원",
    displayName: "월드컵공원",
    category: "공원·자연",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5686,
    lng: 126.897,
    description: "하늘공원·노을공원 포함 대형 공원",
    place: "마포구 상암동",
  },
  {
    areaName: "안양천",
    displayName: "안양천",
    category: "공원·자연",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5271,
    lng: 126.871,
    description: "자전거·조깅 코스가 정비된 하천 공원",
    place: "영등포구 당산동",
  },
  {
    areaName: "서울식물원·마곡나루역",
    displayName: "서울식물원",
    category: "공원·자연",
    operatingHours: { start: 9, end: 18 },
    lat: 37.5685,
    lng: 126.83,
    description: "온실·야외 정원을 갖춘 도시형 식물원",
    place: "강서구 마곡동",
  },

  // ── 한강 ──────────────────────────────────────────────────
  {
    areaName: "여의도한강공원",
    displayName: "여의도한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5284,
    lng: 126.9331,
    description: "서울 대표 한강공원, 넓은 잔디광장",
    place: "영등포구 여의도동",
  },
  {
    areaName: "반포한강공원",
    displayName: "반포한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5102,
    lng: 126.9995,
    description: "달빛무지개분수 야경 명소",
    place: "서초구 반포동",
  },
  {
    areaName: "뚝섬한강공원",
    displayName: "뚝섬한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5296,
    lng: 127.0686,
    description: "수영장·자전거 코스 갖춘 한강공원",
    place: "광진구 자양동",
  },
  {
    areaName: "망원한강공원",
    displayName: "망원한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5551,
    lng: 126.8998,
    description: "망원동 감성 한강 피크닉 명소",
    place: "마포구 망원동",
  },
  {
    areaName: "잠실한강공원",
    displayName: "잠실한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5152,
    lng: 127.0739,
    description: "석촌호수 인접 한강공원",
    place: "송파구 잠실동",
  },
  {
    areaName: "이촌한강공원",
    displayName: "이촌한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5183,
    lng: 126.9714,
    description: "국립중앙박물관 앞 한강공원",
    place: "용산구 이촌동",
  },
  {
    areaName: "난지한강공원",
    displayName: "난지한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5695,
    lng: 126.8861,
    description: "캠핑장과 수상레저를 즐길 수 있는 공원",
    place: "마포구 상암동",
  },
  {
    areaName: "양화한강공원",
    displayName: "양화한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5456,
    lng: 126.9022,
    description: "선유도 인접, 한강 드라이브 명소",
    place: "영등포구 양평동",
  },
  {
    areaName: "강서한강공원",
    displayName: "강서한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.573,
    lng: 126.8236,
    description: "김포공항 인근 넓고 한산한 한강공원",
    place: "강서구 염창동",
  },
  {
    areaName: "광나루한강공원",
    displayName: "광나루한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5487,
    lng: 127.0938,
    description: "아차산 자락 한강 피크닉 명소",
    place: "광진구 광장동",
  },
  {
    areaName: "잠원한강공원",
    displayName: "잠원한강공원",
    category: "한강",
    operatingHours: { start: 0, end: 24 },
    lat: 37.5121,
    lng: 127.0016,
    description: "잠원동 조용한 한강 산책로",
    place: "서초구 잠원동",
  },

  // ── 관광·역사 ────────────────────────────────────────────
  {
    areaName: "경복궁",
    displayName: "경복궁",
    category: "관광·역사",
    operatingHours: { start: 9, end: 18 },
    lat: 37.5796,
    lng: 126.977,
    description: "조선의 법궁, 무료 한복 대여",
    place: "종로구 세종로",
  },
  {
    areaName: "창덕궁·종묘",
    displayName: "창덕궁·종묘",
    category: "관광·역사",
    operatingHours: { start: 9, end: 18 },
    lat: 37.5796,
    lng: 126.9893,
    description: "유네스코 세계문화유산 궁궐",
    place: "종로구 와룡동",
  },
  {
    areaName: "광화문·덕수궁",
    displayName: "광화문·덕수궁",
    category: "관광·역사",
    operatingHours: { start: 9, end: 21 },
    lat: 37.572,
    lng: 126.9769,
    description: "역사와 현대가 공존하는 서울의 중심",
    place: "종로구 세종로",
  },
  {
    areaName: "북촌한옥마을",
    displayName: "북촌한옥마을",
    category: "관광·역사",
    operatingHours: { start: 7, end: 22 },
    lat: 37.5827,
    lng: 126.9843,
    description: "전통 한옥이 모여 있는 고즈넉한 마을",
    place: "종로구 가회동",
  },
  {
    areaName: "인사동",
    displayName: "인사동",
    category: "관광·역사",
    operatingHours: { start: 10, end: 22 },
    lat: 37.5744,
    lng: 126.9855,
    description: "갤러리·전통공예 밀집 문화 거리",
    place: "종로구 인사동",
  },
  {
    areaName: "서촌",
    displayName: "서촌마을",
    category: "관광·역사",
    operatingHours: { start: 9, end: 22 },
    lat: 37.578,
    lng: 126.9697,
    description: "경복궁 서쪽 조용한 골목과 카페",
    place: "종로구 체부동",
  },
  {
    areaName: "익선동",
    displayName: "익선동",
    category: "관광·역사",
    operatingHours: { start: 10, end: 23 },
    lat: 37.5742,
    lng: 126.9986,
    description: "한옥을 개조한 카페·식당 골목",
    place: "종로구 익선동",
  },
  {
    areaName: "남대문시장",
    displayName: "남대문시장",
    category: "관광·역사",
    operatingHours: { start: 9, end: 23 },
    lat: 37.5579,
    lng: 126.9753,
    description: "600년 전통 서울 최대 전통시장",
    place: "중구 남창동",
  },
  {
    areaName: "혜화역",
    displayName: "대학로·혜화",
    category: "관광·역사",
    operatingHours: { start: 10, end: 24 },
    lat: 37.5822,
    lng: 127.0018,
    description: "소극장·공연 문화의 중심지 대학로",
    place: "종로구 혜화동",
  },

  // ── 상권·역세권 ──────────────────────────────────────────
  {
    areaName: "강남 MICE 관광특구",
    displayName: "강남 코엑스",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 24 },
    lat: 37.5012,
    lng: 127.0396,
    description: "코엑스·비즈니스 복합 상권",
    place: "강남구 삼성동",
  },
  {
    areaName: "홍대 관광특구",
    displayName: "홍대",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 24 },
    lat: 37.5563,
    lng: 126.9225,
    description: "젊음의 문화·예술·클럽 거리",
    place: "마포구 서교동",
  },
  {
    areaName: "명동 관광특구",
    displayName: "명동",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 23 },
    lat: 37.5635,
    lng: 126.9858,
    description: "쇼핑·길거리 음식 최대 상권",
    place: "중구 명동",
  },
  {
    areaName: "이태원 관광특구",
    displayName: "이태원",
    category: "상권·역세권",
    operatingHours: { start: 11, end: 24 },
    lat: 37.534,
    lng: 126.994,
    description: "다국적 음식·문화 특구",
    place: "용산구 이태원동",
  },
  {
    areaName: "잠실 관광특구",
    displayName: "잠실",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 23 },
    lat: 37.5115,
    lng: 127.098,
    description: "롯데월드·스타필드 복합 상권",
    place: "송파구 잠실동",
  },
  {
    areaName: "동대문 관광특구",
    displayName: "동대문",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 24 },
    lat: 37.5665,
    lng: 127.009,
    description: "패션·쇼핑 특구, 밤새 운영",
    place: "중구 을지로6가",
  },
  {
    areaName: "강남역",
    displayName: "강남역",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 24 },
    lat: 37.4979,
    lng: 127.0276,
    description: "서울 최대 유동인구 상권",
    place: "강남구 역삼동",
  },
  {
    areaName: "건대입구역",
    displayName: "건대입구",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 24 },
    lat: 37.5403,
    lng: 127.0693,
    description: "건국대 앞 번화가·클럽 거리",
    place: "광진구 화양동",
  },
  {
    areaName: "왕십리역",
    displayName: "왕십리",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 24 },
    lat: 37.5613,
    lng: 127.0374,
    description: "성동구 쇼핑·맛집 상권",
    place: "성동구 행당동",
  },
  {
    areaName: "합정역",
    displayName: "합정",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 24 },
    lat: 37.5498,
    lng: 126.9143,
    description: "마포구 감성 카페·레스토랑 거리",
    place: "마포구 합정동",
  },
  {
    areaName: "서울역",
    displayName: "서울역",
    category: "상권·역세권",
    operatingHours: { start: 6, end: 24 },
    lat: 37.5547,
    lng: 126.9707,
    description: "교통 허브, 롯데마트·쇼핑 밀집",
    place: "중구 봉래동",
  },
  {
    areaName: "용산역",
    displayName: "용산",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 24 },
    lat: 37.5298,
    lng: 126.9649,
    description: "용산 전자상가·아이파크몰",
    place: "용산구 한강로",
  },
  {
    areaName: "동대문역",
    displayName: "동대문역",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 24 },
    lat: 37.5717,
    lng: 127.0093,
    description: "DDP·광장시장 인근 상권",
    place: "종로구 예지동",
  },
  {
    areaName: "선릉역",
    displayName: "선릉역",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 23 },
    lat: 37.5045,
    lng: 127.0489,
    description: "강남 비즈니스·맛집 밀집 상권",
    place: "강남구 대치동",
  },
  {
    areaName: "역삼역",
    displayName: "역삼역",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 23 },
    lat: 37.5007,
    lng: 127.0364,
    description: "강남 오피스·스타트업 중심 상권",
    place: "강남구 역삼동",
  },
  {
    areaName: "영등포 타임스퀘어",
    displayName: "영등포 타임스퀘어",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 23 },
    lat: 37.5157,
    lng: 126.9007,
    description: "영등포 최대 쇼핑몰 복합상권",
    place: "영등포구 영등포동",
  },
  {
    areaName: "신도림역",
    displayName: "신도림",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 23 },
    lat: 37.5086,
    lng: 126.8912,
    description: "디큐브시티·테크노마트 상권",
    place: "구로구 신도림동",
  },
  {
    areaName: "구로디지털단지역",
    displayName: "구로디지털단지",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 22 },
    lat: 37.4851,
    lng: 126.9011,
    description: "IT기업 밀집 디지털 산업단지",
    place: "구로구 구로동",
  },
  {
    areaName: "가산디지털단지역",
    displayName: "가산디지털단지",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 22 },
    lat: 37.4818,
    lng: 126.8827,
    description: "패션아울렛·IT단지 복합 상권",
    place: "금천구 가산동",
  },
  {
    areaName: "신림역",
    displayName: "신림",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 24 },
    lat: 37.4841,
    lng: 126.9295,
    description: "서울대 인근 대학가 상권",
    place: "관악구 신림동",
  },
  {
    areaName: "사당역",
    displayName: "사당",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 24 },
    lat: 37.4767,
    lng: 126.9815,
    description: "강남권 교통 요충지 상권",
    place: "동작구 사당동",
  },
  {
    areaName: "교대역",
    displayName: "교대",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 23 },
    lat: 37.4934,
    lng: 127.0138,
    description: "서초구 법조타운·강남 상권",
    place: "서초구 서초동",
  },
  {
    areaName: "고속터미널역",
    displayName: "고속터미널",
    category: "상권·역세권",
    operatingHours: { start: 6, end: 24 },
    lat: 37.5048,
    lng: 127.0047,
    description: "센트럴시티·파미에스트리트 쇼핑",
    place: "서초구 반포동",
  },
  {
    areaName: "노량진",
    displayName: "노량진",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 23 },
    lat: 37.5132,
    lng: 126.943,
    description: "수산시장·고시촌 밀집 지역",
    place: "동작구 노량진동",
  },
  {
    areaName: "연남동",
    displayName: "연남동",
    category: "상권·역세권",
    operatingHours: { start: 11, end: 24 },
    lat: 37.5615,
    lng: 126.9236,
    description: "경의선 숲길과 감성 카페·식당",
    place: "마포구 연남동",
  },
  {
    areaName: "성수카페거리",
    displayName: "성수 카페거리",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 23 },
    lat: 37.5444,
    lng: 127.0564,
    description: "힙한 카페·팝업 스토어 밀집",
    place: "성동구 성수동",
  },
  {
    areaName: "여의도",
    displayName: "여의도",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 23 },
    lat: 37.5219,
    lng: 126.9247,
    description: "금융·방송·벚꽃 명소",
    place: "영등포구 여의도동",
  },
  {
    areaName: "연신내역",
    displayName: "연신내",
    category: "상권·역세권",
    operatingHours: { start: 7, end: 23 },
    lat: 37.6189,
    lng: 126.9196,
    description: "은평구 최대 상권",
    place: "은평구 불광동",
  },
  {
    areaName: "천호역",
    displayName: "천호",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 23 },
    lat: 37.5386,
    lng: 127.1237,
    description: "강동구 대표 쇼핑·먹자골목",
    place: "강동구 천호동",
  },
  {
    areaName: "회기역",
    displayName: "회기",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 22 },
    lat: 37.5928,
    lng: 127.0556,
    description: "경희대·외대 인근 대학가 상권",
    place: "동대문구 회기동",
  },
  {
    areaName: "잠실새내역",
    displayName: "잠실새내",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 23 },
    lat: 37.5099,
    lng: 127.0856,
    description: "잠실 먹자골목·카페 밀집",
    place: "송파구 신천동",
  },
  {
    areaName: "뚝섬역",
    displayName: "뚝섬역",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 23 },
    lat: 37.5479,
    lng: 127.0476,
    description: "성수·뚝섬 인근 카페·상권",
    place: "성동구 성수동",
  },
  {
    areaName: "군자역",
    displayName: "군자",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 22 },
    lat: 37.557,
    lng: 127.0802,
    description: "광진·중랑 접경 생활 상권",
    place: "광진구 군자동",
  },
  {
    areaName: "가락시장",
    displayName: "가락시장",
    category: "상권·역세권",
    operatingHours: { start: 6, end: 20 },
    lat: 37.4923,
    lng: 127.1157,
    description: "국내 최대 농수산물 도매시장",
    place: "송파구 가락동",
  },
  {
    areaName: "장지역",
    displayName: "장지역",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 22 },
    lat: 37.4744,
    lng: 127.1449,
    description: "문정 법조단지·가든파이브 상권",
    place: "송파구 장지동",
  },
  {
    areaName: "쌍문역",
    displayName: "쌍문",
    category: "상권·역세권",
    operatingHours: { start: 8, end: 22 },
    lat: 37.6488,
    lng: 127.0275,
    description: "도봉구 생활 밀착형 상권",
    place: "도봉구 쌍문동",
  },
  {
    areaName: "성신여대입구역",
    displayName: "성신여대입구",
    category: "상권·역세권",
    operatingHours: { start: 10, end: 23 },
    lat: 37.5924,
    lng: 127.0165,
    description: "돈암동 여대 상권·먹자골목",
    place: "성북구 돈암동",
  },
  {
    areaName: "미아사거리역",
    displayName: "미아사거리",
    category: "상권·역세권",
    operatingHours: { start: 9, end: 22 },
    lat: 37.613,
    lng: 127.0246,
    description: "강북구 교통 요충 상권",
    place: "강북구 미아동",
  },
  {
    areaName: "김포공항",
    displayName: "김포공항",
    category: "상권·역세권",
    operatingHours: { start: 5, end: 24 },
    lat: 37.5583,
    lng: 126.7906,
    description: "국내선 허브, 공항상업시설",
    place: "강서구 공항동",
  },

  // ── 야경·전망 — 저녁 17시 이후에만 추천 ────────────────
  {
    areaName: "노들섬",
    displayName: "노들섬",
    category: "야경·전망",
    operatingHours: { start: 17, end: 24 },
    lat: 37.5171,
    lng: 126.9378,
    description: "한강 위 섬에서 즐기는 야경과 음악",
    place: "용산구 이촌동",
  },
];

export function isPlaceOpen(place: SeoulPlace, hour: number): boolean {
  const { start, end } = place.operatingHours;
  return hour >= start && hour < end;
}
